import React, { useEffect, useState } from "react";
import api, { downloadArtifact } from "@/lib/api";
import { AppShell } from "@/components/layout/AppShell";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Disclaimer } from "@/components/common/Disclaimer";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { toast } from "sonner";
import { Download, Package, FileText, FileSpreadsheet, Search, FileCheck } from "lucide-react";

const fmtIcon = (f) => (f === "XLSX" ? FileSpreadsheet : f === "PDF" ? FileCheck : FileText);

export default function Downloads() {
  const [data, setData] = useState({ published: false, documents: [] });
  const [q, setQ] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => { api.get("/downloads").then((r) => setData(r.data)).catch(() => {}).finally(() => setLoading(false)); }, []);

  const zip = data.documents.find((d) => d.format === "ZIP");
  const docs = data.documents.filter((d) => d.format !== "ZIP").filter((d) => d.title.toLowerCase().includes(q.toLowerCase()) || d.doc_id.toLowerCase().includes(q.toLowerCase()));

  const dl = async (d) => { try { await downloadArtifact(d.id, d.filename); } catch { toast.error("Download failed"); } };

  return (
    <AppShell>
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <div><h1 className="text-2xl font-display">Downloads</h1><p className="text-sm text-[hsl(var(--muted-foreground))]">Your generated toolkit documents.</p></div>
        {zip && <Button size="lg" onClick={() => dl(zip)} data-testid="download-zip-button"><Package className="h-4 w-4 mr-2" />Download full ZIP</Button>}
      </div>

      {loading ? <div className="text-[hsl(var(--muted-foreground))]">Loading…</div> : data.documents.length === 0 ? (
        <Card className="card-shadow p-10 text-center">
          <Download className="h-10 w-10 mx-auto text-[hsl(var(--muted-foreground))]" />
          <p className="mt-3 font-medium">No documents yet</p>
          <p className="text-sm text-[hsl(var(--muted-foreground))]">Documents appear here after your onboarding is approved and generated by FaizZab.</p>
        </Card>
      ) : (
        <>
          <div className="mb-4 flex items-center gap-3">
            <StatusBadge status={data.published ? "published" : "generated"} />
            <span className="text-sm text-[hsl(var(--muted-foreground))]">{docs.length} documents</span>
          </div>
          <Disclaimer>These documents are templates branded for your organization. They require implementation and, for DPDPA, independent legal review. Generation does not guarantee certification.</Disclaimer>
          <div className="mt-4 relative max-w-sm"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-[hsl(var(--muted-foreground))]" /><Input className="pl-9" placeholder="Search documents…" value={q} onChange={(e) => setQ(e.target.value)} data-testid="downloads-search" /></div>
          <Card className="card-shadow mt-4 overflow-hidden">
            <div className="max-h-[600px] overflow-auto">
              <Table>
                <TableHeader className="sticky top-0 bg-white z-10"><TableRow><TableHead className="w-[110px]">Doc ID</TableHead><TableHead>Document</TableHead><TableHead className="w-[90px]">Format</TableHead><TableHead className="hidden md:table-cell">Version</TableHead><TableHead className="w-[60px]"></TableHead></TableRow></TableHeader>
                <TableBody>
                  {docs.map((d) => { const Icon = fmtIcon(d.format); return (
                    <TableRow key={d.id} data-testid={`download-row-${d.doc_id}-${d.format}`}>
                      <TableCell className="font-mono text-xs">{d.doc_id}</TableCell>
                      <TableCell><div className="font-medium">{d.title}</div><div className="text-xs text-[hsl(var(--muted-foreground))]">{d.template_class}</div></TableCell>
                      <TableCell><Badge variant="outline" className="gap-1"><Icon className="h-3 w-3" />{d.format}</Badge></TableCell>
                      <TableCell className="hidden md:table-cell font-mono text-xs">{d.version}</TableCell>
                      <TableCell><Button size="icon" variant="ghost" onClick={() => dl(d)} data-testid={`download-btn-${d.id}`}><Download className="h-4 w-4" /></Button></TableCell>
                    </TableRow>
                  ); })}
                </TableBody>
              </Table>
            </div>
          </Card>
        </>
      )}
    </AppShell>
  );
}
